(() => {
  const API_BASE = 'https://wuwa-uzbek-language-two.vercel.app/api';
  const $ = (s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const L=()=>localStorage.getItem('wuwa-language')||'en';
  const T={en:{chat:'GLOBAL CHAT',sub:'Talk with Rovers around the world',name:'Nickname',namePh:'Your Rover name',msgPh:'Say hello to the global community…',send:'SEND',empty:'No messages yet. Be the first Rover!',thanks:'Your support has been recorded.',dup:'This email has already supported the campaign.',error:'Something went wrong. Please try again.',privacy:'Never post private information.'},uz:{chat:'GLOBAL CHAT',sub:'Butun dunyodagi Roverlar bilan suhbatlashing',name:'Taxallus',namePh:'Rover taxallusingiz',msgPh:'Global jamoaga salom yo‘llang…',send:'YUBORISH',empty:'Hozircha xabarlar yo‘q. Birinchi Rover bo‘ling!',thanks:'Qo‘llab-quvvatlashingiz saqlandi.',dup:'Bu email allaqachon kampaniyani qo‘llab-quvvatlagan.',error:'Nimadir xato ketdi. Qayta urinib ko‘ring.',privacy:'Shaxsiy ma’lumotlarni yozmang.'},ru:{chat:'ГЛОБАЛЬНЫЙ ЧАТ',sub:'Общайтесь с Роверами со всего мира',name:'Имя',namePh:'Ваше имя Ровера',msgPh:'Поздоровайтесь с сообществом…',send:'ОТПРАВИТЬ',empty:'Сообщений пока нет. Будьте первым!',thanks:'Ваша поддержка записана.',dup:'Этот email уже поддержал кампанию.',error:'Произошла ошибка. Попробуйте ещё раз.',privacy:'Не публикуйте личные данные.'},ja:{chat:'GLOBAL CHAT',sub:'世界中のRoverと交流しましょう',name:'ニックネーム',namePh:'Rover名',msgPh:'コミュニティに挨拶しましょう…',send:'送信',empty:'まだメッセージはありません。',thanks:'応援を記録しました。',dup:'このメールはすでに登録されています。',error:'エラーが発生しました。',privacy:'個人情報を投稿しないでください。'},ko:{chat:'GLOBAL CHAT',sub:'전 세계 Rover들과 이야기하세요',name:'닉네임',namePh:'Rover 이름',msgPh:'글로벌 커뮤니티에 인사를 남겨보세요…',send:'보내기',empty:'아직 메시지가 없습니다.',thanks:'응원이 기록되었습니다.',dup:'이 이메일은 이미 등록되었습니다.',error:'문제가 발생했습니다.',privacy:'개인정보를 게시하지 마세요.'},'zh-CN':{chat:'全球聊天',sub:'与来自世界各地的Rover交流',name:'昵称',namePh:'你的Rover昵称',msgPh:'向全球社区打个招呼…',send:'发送',empty:'还没有消息。',thanks:'您的支持已记录。',dup:'这个邮箱已经支持过本活动。',error:'发生错误，请重试。',privacy:'请勿发布个人信息。'}};
  const t=()=>T[L()]||T.en;
  const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};
  const flag=c=>{c=String(c||'XX').toUpperCase();return /^[A-Z]{2}$/.test(c)&&c!=='XX'?[...c].map(x=>String.fromCodePoint(127397+x.charCodeAt())).join(''):'🌍'};
  const ago=x=>{let s=Math.max(0,Math.floor((Date.now()-new Date(x))/1000));return s<60?s+'s':s<3600?Math.floor(s/60)+'m':s<86400?Math.floor(s/3600)+'h':Math.floor(s/86400)+'d'};
  function styles(){let s=document.createElement('style');s.textContent='.live-chat-section{padding-top:2rem}.chat-panel{display:grid;grid-template-columns:1fr 1.25fr;border:1px solid rgba(255,255,255,.12);background:rgba(10,14,19,.8);overflow:hidden}.chat-intro{padding:clamp(28px,5vw,64px);border-right:1px solid rgba(255,255,255,.1)}.chat-intro h2{font-family:Space Grotesk,sans-serif;font-size:clamp(40px,6vw,78px);line-height:.9;margin:18px 0 22px}.chat-sub{color:#a9b2c1;line-height:1.7}.chat-note{margin-top:40px;padding:14px;border-left:2px solid #c7ff21;color:#8993a2;font-size:12px}.chat-live,.live-status{color:#c7ff21;font-size:11px;letter-spacing:.15em;font-weight:800}.chat-box{display:flex;flex-direction:column;min-width:0}.chat-toolbar{padding:18px 20px;border-bottom:1px solid rgba(255,255,255,.1);display:flex;justify-content:space-between}.chat-messages{height:400px;overflow:auto;padding:20px}.chat-message{display:flex;gap:12px;margin-bottom:18px}.chat-avatar{width:34px;height:34px;flex:none;display:grid;place-items:center;background:#11171e;border:1px solid rgba(199,255,33,.35)}.chat-meta{display:flex;gap:8px;align-items:baseline;flex-wrap:wrap}.chat-name{font-weight:800;font-size:13px}.chat-time{color:#697484;font-size:10px}.chat-text{color:#c7cdd7;font-size:13px;line-height:1.5;margin-top:4px;word-break:break-word}.chat-empty{height:100%;display:grid;place-items:center;text-align:center;color:#778191;font-size:13px}.chat-form{padding:18px;border-top:1px solid rgba(255,255,255,.1)}.chat-form-grid{display:grid;grid-template-columns:150px 1fr auto;gap:8px}.chat-form input{box-sizing:border-box;width:100%;background:#080c11;border:1px solid rgba(255,255,255,.15);color:#fff;padding:13px;font:inherit}.chat-form button{border:0;background:#c7ff21;color:#080b10;padding:0 18px;font-weight:900;cursor:pointer}.chat-form button:disabled{opacity:.5}.chat-privacy{display:block;color:#667181;font-size:10px;margin-top:8px}@media(max-width:800px){.chat-panel{grid-template-columns:1fr}.chat-intro{border-right:0;border-bottom:1px solid rgba(255,255,255,.1)}.chat-form-grid{grid-template-columns:1fr 1fr}.chat-form button{grid-column:1/-1;min-height:46px}}';document.head.appendChild(s)}
  function add(){if($('#global-chat'))return;let s=document.createElement('section');s.className='section live-chat-section';s.id='global-chat';s.innerHTML=`<div class="chat-panel reveal visible"><div class="chat-intro"><span class="section-kicker">09 /</span><div class="chat-live">● LIVE COMMUNITY</div><h2>${esc(t().chat)}</h2><p class="chat-sub">${esc(t().sub)}</p><div class="chat-note">${esc(t().privacy)}</div></div><div class="chat-box"><div class="chat-toolbar"><span>${esc(t().chat)}</span><span class="live-status">● LIVE</span></div><div class="chat-messages" id="chatMessages"><div class="chat-empty">Loading…</div></div><form class="chat-form" id="chatForm"><div class="chat-form-grid"><input id="chatNickname" maxlength="32" placeholder="${esc(t().namePh)}"><input id="chatMessage" maxlength="500" required placeholder="${esc(t().msgPh)}"><button id="chatSend">${esc(t().send)}</button></div><small class="chat-privacy">${esc(t().privacy)}</small></form></div></div>`;let f=$('.site-footer');(f?.parentNode||document.body).insertBefore(s,f||null);$('#chatForm').addEventListener('submit',send);load()}
  function render(ms){let b=$('#chatMessages');if(!b)return;if(!ms?.length){b.innerHTML=`<div class="chat-empty">${esc(t().empty)}</div>`;return}b.innerHTML=ms.map(m=>`<article class="chat-message"><div class="chat-avatar">${flag(m.country)}</div><div><div class="chat-meta"><span class="chat-name">${esc(m.nickname)}</span><span>${flag(m.country)}</span><span class="chat-time">${ago(m.createdAt)}</span></div><div class="chat-text">${esc(m.message)}</div></div></article>`).join('');b.scrollTop=b.scrollHeight}
  async function load(){try{let r=await fetch(API_BASE+'/chat',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw 0;render(d.messages)}catch{let b=$('#chatMessages');if(b)b.innerHTML=`<div class="chat-empty">${esc(t().error)}</div>`}}
  async function send(e){e.preventDefault();let b=$('#chatSend'),m=$('#chatMessage').value.trim();if(!m)return;b.disabled=true;try{let r=await fetch(API_BASE+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nickname:$('#chatNickname').value.trim(),message:m})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||t().error);$('#chatMessage').value='';await load();if(window.showToast)showToast('✓ '+(t().thanks||'Sent'))}catch(x){if(window.showToast)showToast(x.message)}finally{b.disabled=false}}
  function vote(){let old=$('#voteForm');if(!old)return;let f=old.cloneNode(true);old.replaceWith(f);f.addEventListener('submit',async e=>{e.preventDefault();let email=$('#email').value.trim(),b=f.querySelector('button');if(!email)return;b.disabled=true;try{let r=await fetch(API_BASE+'/vote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(r.status===409?t().dup:d.error||t().error);$$('.counter').forEach(x=>x.textContent=Number(d.total).toLocaleString('en-US'));$('#voteNotice').hidden=false;$('#voteNotice').textContent=t().thanks;f.reset();if(window.showToast)showToast(t().thanks)}catch(x){$('#voteNotice').hidden=false;$('#voteNotice').textContent=x.message;$('#voteNotice').classList.add('api-error')}finally{b.disabled=false}})}
  async function stats(){try{let r=await fetch(API_BASE+'/stats',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw 0;$$('.counter').forEach(x=>x.textContent=Number(d.total).toLocaleString('en-US'));let p=Math.min(100,Number(d.total)/50000*100),bar=$('.progress span'),g=$('.goal-top strong');if(bar)bar.style.width=p+'%';if(g)g.textContent=p.toFixed(1)+'%';}catch{}}
  function init(){styles();add();vote();stats();setInterval(stats,15000);setInterval(load,8000)}document.addEventListener('DOMContentLoaded',init);
})();
