(() => {
  const API_BASE = window.WUWA_API_BASE || 'https://wuwa-uzbek-language-two.vercel.app/api';
  const $ = (s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
  const tr = (k, f=k) => window.I18N?.t(k, f) ?? f;
  const esc=v=>{const d=document.createElement('div');d.textContent=v??'';return d.innerHTML};
  const flag=c=>{c=String(c||'XX').toUpperCase();return /^[A-Z]{2}$/.test(c)&&c!=='XX'?[...c].map(x=>String.fromCodePoint(127397+x.charCodeAt())).join(''):'🌍'};
  const ago=x=>{const s=Math.max(0,Math.floor((Date.now()-new Date(x))/1000));return s<60?s+'s':s<3600?Math.floor(s/60)+'m':s<86400?Math.floor(s/3600)+'h':Math.floor(s/86400)+'d'};

  function styles(){const s=document.createElement('style');s.textContent='.live-chat-section{padding-top:2rem}.chat-panel{display:grid;grid-template-columns:1fr 1.25fr;border:1px solid rgba(255,255,255,.12);background:rgba(10,14,19,.8);overflow:hidden}.chat-intro{padding:clamp(28px,5vw,64px);border-right:1px solid rgba(255,255,255,.1)}.chat-intro h2{font-family:Space Grotesk,sans-serif;font-size:clamp(40px,6vw,78px);line-height:.9;margin:18px 0 22px}.chat-sub{color:#a9b2c1;line-height:1.7}.chat-note{margin-top:40px;padding:14px;border-left:2px solid #c7ff21;color:#8993a2;font-size:12px}.chat-live,.live-status{color:#c7ff21;font-size:11px;letter-spacing:.15em;font-weight:800}.chat-box{display:flex;flex-direction:column;min-width:0}.chat-toolbar{padding:18px 20px;border-bottom:1px solid rgba(255,255,255,.1);display:flex;justify-content:space-between}.chat-messages{height:400px;overflow:auto;padding:20px}.chat-message{display:flex;gap:12px;margin-bottom:18px}.chat-avatar{width:34px;height:34px;flex:none;display:grid;place-items:center;background:#11171e;border:1px solid rgba(199,255,33,.35)}.chat-meta{display:flex;gap:8px;align-items:baseline;flex-wrap:wrap}.chat-name{font-weight:800;font-size:13px}.chat-time{color:#697484;font-size:10px}.chat-text{color:#c7cdd7;font-size:13px;line-height:1.5;margin-top:4px;word-break:break-word}.chat-empty{height:100%;display:grid;place-items:center;text-align:center;color:#778191;font-size:13px}.chat-form{padding:18px;border-top:1px solid rgba(255,255,255,.1)}.chat-form-grid{display:grid;grid-template-columns:150px 1fr auto;gap:8px}.chat-form input{box-sizing:border-box;width:100%;background:#080c11;border:1px solid rgba(255,255,255,.15);color:#fff;padding:13px;font:inherit}.chat-form button{border:0;background:#c7ff21;color:#080b10;padding:0 18px;font-weight:900;cursor:pointer}.chat-form button:disabled{opacity:.5}.chat-privacy{display:block;color:#667181;font-size:10px;margin-top:8px}@media(max-width:800px){.chat-panel{grid-template-columns:1fr}.chat-intro{border-right:0;border-bottom:1px solid rgba(255,255,255,.1)}.chat-form-grid{grid-template-columns:1fr 1fr}.chat-form button{grid-column:1/-1;min-height:46px}}';document.head.appendChild(s)}
  function add(){if($('#global-chat'))return;const s=document.createElement('section');s.className='section live-chat-section';s.id='global-chat';s.innerHTML=`<div class="chat-panel reveal visible"><div class="chat-intro"><span class="section-kicker">09 /</span><div class="chat-live">● ${esc(tr('chatLive','LIVE COMMUNITY'))}</div><h2>${esc(tr('chat','GLOBAL CHAT'))}</h2><p class="chat-sub">${esc(tr('chatSub','Talk with Rovers around the world'))}</p><div class="chat-note">${esc(tr('chatPrivacy','Never post private information.'))}</div></div><div class="chat-box"><div class="chat-toolbar"><span>${esc(tr('chat','GLOBAL CHAT'))}</span><span class="live-status">● ${esc(tr('chatLive','LIVE'))}</span></div><div class="chat-messages" id="chatMessages"><div class="chat-empty">${esc(tr('chatLoading','Loading…'))}</div></div><form class="chat-form" id="chatForm"><div class="chat-form-grid"><input id="chatNickname" maxlength="32" placeholder="${esc(tr('chatNamePh','Your Rover name'))}"><input id="chatMessage" maxlength="500" required placeholder="${esc(tr('chatMsgPh','Say hello to the global community…'))}"><button id="chatSend">${esc(tr('chatSend','SEND'))}</button></div><small class="chat-privacy">${esc(tr('chatPrivacy','Never post private information.'))}</small></form></div></div>`;const f=$('.site-footer');(f?.parentNode||document.body).insertBefore(s,f||null);$('#chatForm').addEventListener('submit',send);load()}
  function render(ms){const b=$('#chatMessages');if(!b)return;if(!ms?.length){b.innerHTML=`<div class="chat-empty">${esc(tr('chatEmpty','No messages yet. Be the first Rover!'))}</div>`;return}b.innerHTML=ms.map(m=>`<article class="chat-message"><div class="chat-avatar">${flag(m.country)}</div><div><div class="chat-meta"><span class="chat-name">${esc(m.nickname)}</span><span>${flag(m.country)}</span><span class="chat-time">${ago(m.createdAt)}</span></div><div class="chat-text">${esc(m.message)}</div></div></article>`).join('');b.scrollTop=b.scrollHeight}
  async function load(){try{const r=await fetch(API_BASE+'/chat',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw 0;render(d.messages)}catch{const b=$('#chatMessages');if(b)b.innerHTML=`<div class="chat-empty">${esc(tr('error','Something went wrong. Please try again.'))}</div>`}}
  async function send(e){e.preventDefault();const b=$('#chatSend'),m=$('#chatMessage').value.trim();if(!m)return;b.disabled=true;try{const r=await fetch(API_BASE+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nickname:$('#chatNickname').value.trim(),message:m,country:$('#country')?.value||'XX'})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||tr('error'));$('#chatMessage').value='';await load();window.showToast?.('✓ '+tr('thanks','Your support has been recorded.'))}catch(x){window.showToast?.(x.message)}finally{b.disabled=false}}
  function vote(){const f=$('#voteForm');if(!f)return;f.addEventListener('submit',async e=>{e.preventDefault();const email=$('#email').value.trim(),country=$('#country')?.value||'XX',b=f.querySelector('button');if(!email||country==='XX'){window.showToast?.(tr('countryRequired','Please select your country.'));return}b.disabled=true;try{const r=await fetch(API_BASE+'/vote',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,country})}),d=await r.json();if(!r.ok||!d.ok)throw new Error(r.status===409?tr('duplicate'):r.status===429?tr('voteRate'):d.error||tr('error'));$$('.counter').forEach(x=>x.textContent=Number(d.total).toLocaleString('en-US'));$('#voteNotice').hidden=false;$('#voteNotice').textContent=tr('thanks');$('#voteNotice').classList.remove('api-error');f.reset();if($('#country'))$('#country').value=country;window.showToast?.(tr('thanks'))}catch(x){$('#voteNotice').hidden=false;$('#voteNotice').textContent=x.message;$('#voteNotice').classList.add('api-error')}finally{b.disabled=false}})}
  async function stats(){try{const r=await fetch(API_BASE+'/stats',{cache:'no-store'}),d=await r.json();if(!r.ok||!d.ok)throw 0;$$('.counter').forEach(x=>x.textContent=Number(d.total).toLocaleString('en-US'));const p=Math.min(100,Number(d.total)/50000*100),bar=$('.progress span'),g=$('.goal-top strong');if(bar)bar.style.width=p+'%';if(g)g.textContent=p.toFixed(1)+'%';renderCountries(d.countries||[])}catch{}}
  function renderCountries(rows){const list=$('.country-list');if(!list||!rows.length)return;const dn=(()=>{try{return new Intl.DisplayNames([window.I18N?.language||'en','en'],{type:'region'})}catch{return null}})();const name=c=>dn?.of(c)||c;list.innerHTML=rows.slice(0,8).map(x=>{const code=String(x.country||x.country_code||'XX').toUpperCase();return `<div class="country-row"><span>${flag(code)} ${esc(name(code))}</span><strong>${Number(x.count||x.total||0).toLocaleString('en-US')}</strong></div>`}).join('')}
  function refreshDynamicText(){const s=$('#global-chat');if(!s)return;s.querySelector('.chat-live').textContent='● '+tr('chatLive','LIVE COMMUNITY');s.querySelector('.chat-intro h2').textContent=tr('chat','GLOBAL CHAT');s.querySelector('.chat-sub').textContent=tr('chatSub');s.querySelector('.chat-note').textContent=tr('chatPrivacy');s.querySelector('.chat-toolbar span:first-child').textContent=tr('chat');s.querySelector('.live-status').textContent='● '+tr('chatLive','LIVE');s.querySelector('#chatNickname').placeholder=tr('chatNamePh');s.querySelector('#chatMessage').placeholder=tr('chatMsgPh');s.querySelector('#chatSend').textContent=tr('chatSend');s.querySelector('.chat-privacy').textContent=tr('chatPrivacy');load()}
  function init(){styles();add();vote();stats();window.I18N?.onChange(refreshDynamicText);setInterval(stats,15000);setInterval(load,8000)}
  document.addEventListener('DOMContentLoaded',()=>window.I18N?.ready ? window.I18N.ready.then(init) : init());
})();
